### ISSUE TITLE
Issues in example?

### ISSUE THREAD

**Issue by cpr-mab** [CommonplaceRobotics/CRI-Python-Lib#3]
To my understanding the following example makes the robot move 20mm in X, Y and Z and back at 10mm/s.
- The comment implies a different motion
- At 10mm/s it should take at least 2000ms, more than the given timeout

https://github.com/CommonplaceRobotics/CRI-Python-Lib/blob/d5931091940f2fa0e740c82ca6b3da0462eb141b/examples/relative_move.py#L26-L28

**Comment by cpr-bar** [comment]
I corrected the comment in version 0.2.0. The timeout is ok since it is in seconds as floating point.

**Comment by cpr-bar** [comment]
I corrected the comment in version 0.2.0. 
The timeout is ok since it is in seconds as floating point.
